services:
  k7-peer-a:
    build: .
    ports:
      - "5080:8080"
    environment:
      - Database__Provider=Sqlite
      - Database__Name=/data/k7-a
      - BaseUrl=http://k7-peer-a:8080
      - Security__ForceHttps=false
      - Paths__Config=/data/config-a
      - Paths__Metadatas=/data/metadatas-a
      - Paths__Logs=/data/logs-a
      - Paths__Transcoding=/data/transcoding-a
      - Authentication__Local__SignInEnabled=true
      - Authentication__Local__RegistrationEnabled=true
    volumes:
      - "${K7_FED_DATA:-./.federation}/peer-a/data:/data:rw"
      - "${K7_FED_DATA:-./.federation}/media-a:/media:ro"

  k7-peer-b:
    build: .
    ports:
      - "5081:8080"
    environment:
      - Database__Provider=Sqlite
      - Database__Name=/data/k7-b
      - BaseUrl=http://k7-peer-b:8080
      - Security__ForceHttps=false
      - Paths__Config=/data/config-b
      - Paths__Metadatas=/data/metadatas-b
      - Paths__Logs=/data/logs-b
      - Paths__Transcoding=/data/transcoding-b
      - Authentication__Local__SignInEnabled=true
      - Authentication__Local__RegistrationEnabled=true
    volumes:
      - "${K7_FED_DATA:-./.federation}/peer-b/data:/data:rw"
      - "${K7_FED_DATA:-./.federation}/media-b:/media:ro"
