// <auto-generated />
using System;
using MediaServer.Infrastructure.Context.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaServer.Infrastructure.DatabaseProviders.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaServer.Domain.Entities.ExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseMetadataId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseMetadataId");

                    b.HasIndex("MediaId");

                    b.ToTable("ExternalIds");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.IndexedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSplitPart")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentDirectory")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MediaId");

                    b.ToTable("IndexedFiles");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("RootPathAccessible")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MetadataId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("MediaPictures");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.BaseMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.BaseMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("Metadatas");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Ratings.BaseRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("MaximumValue")
                        .HasColumnType("double precision");

                    b.Property<int>("MetadataId")
                        .HasColumnType("integer");

                    b.Property<double>("MinimumValue")
                        .HasColumnType("double precision");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Ratings");

                    b.HasDiscriminator<int>("Source");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthenticationProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MediaServer.Infrastructure.Context.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.Movie", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicAlbum", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.HasIndex("ArtistId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicArtist", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicTrack", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Medias", t =>
                        {
                            t.Property("ArtistId")
                                .HasColumnName("MusicTrack_ArtistId");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.Serie", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.Property<DateOnly?>("ReleaseYear")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.SerieEpisode", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SerieId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SerieId");

                    b.ToTable("Medias", t =>
                        {
                            t.Property("Number")
                                .HasColumnName("SerieEpisode_Number");

                            t.Property("Title")
                                .HasColumnName("SerieEpisode_Title");
                        });

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.SerieSeason", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Medias.BaseMedia");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer");

                    b.HasIndex("SerieId");

                    b.ToTable("Medias", t =>
                        {
                            t.Property("Number")
                                .HasColumnName("SerieSeason_Number");

                            t.Property("SerieId")
                                .HasColumnName("SerieSeason_SerieId");
                        });

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.MovieMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.Property<string[]>("Genres")
                        .HasColumnType("text[]");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.MusicAlbumMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.MusicArtistMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.MusicTrackMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.SerieEpisodeMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.SerieMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.SerieSeasonMetadata", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Metadatas.BaseMetadata");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Ratings.MetadataProviderRating", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Ratings.BaseRating");

                    b.Property<int>("MetadataProvider")
                        .HasColumnType("integer");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Ratings.UserRating", b =>
                {
                    b.HasBaseType("MediaServer.Domain.Entities.Ratings.BaseRating");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.ExternalId", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Metadatas.BaseMetadata", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("BaseMetadataId");

                    b.HasOne("MediaServer.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.IndexedFile", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Library", null)
                        .WithMany("IndexedFiles")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("IndexedFiles")
                        .HasForeignKey("MediaId");

                    b.OwnsOne("MediaServer.Domain.ValueObjects.MediaIdentification", "Identification", b1 =>
                        {
                            b1.Property<int>("IndexedFileId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("ReleaseYear")
                                .HasColumnType("date");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IndexedFileId");

                            b1.ToTable("IndexedFiles");

                            b1.WithOwner()
                                .HasForeignKey("IndexedFileId");
                        });

                    b.Navigation("Identification");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaPicture", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Metadatas.BaseMetadata", "Metadata")
                        .WithMany("Pictures")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.BaseMetadata", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithOne("Metadata")
                        .HasForeignKey("MediaServer.Domain.Entities.Metadatas.BaseMetadata", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Ratings.BaseRating", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Metadatas.BaseMetadata", "Metadata")
                        .WithMany("Ratings")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MediaServer.Infrastructure.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MediaServer.Infrastructure.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaServer.Infrastructure.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MediaServer.Infrastructure.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicAlbum", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Medias.MusicArtist", "Artist")
                        .WithMany("Album")
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicTrack", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Medias.MusicAlbum", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId");

                    b.HasOne("MediaServer.Domain.Entities.Medias.MusicArtist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId");

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.SerieEpisode", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Medias.SerieSeason", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId");

                    b.HasOne("MediaServer.Domain.Entities.Medias.Serie", "Serie")
                        .WithMany("Episodes")
                        .HasForeignKey("SerieId");

                    b.Navigation("Season");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.SerieSeason", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Medias.Serie", "Serie")
                        .WithMany("Seasons")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Ratings.UserRating", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.Users.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Library", b =>
                {
                    b.Navigation("IndexedFiles");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.BaseMedia", b =>
                {
                    b.Navigation("IndexedFiles");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Metadatas.BaseMetadata", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("Pictures");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicAlbum", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.MusicArtist", b =>
                {
                    b.Navigation("Album");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.Serie", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Medias.SerieSeason", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
