<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>K7.Import.UnitTests</RootNamespace>
        <AssemblyName>K7.Import.UnitTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="nunit" />
        <PackageReference Include="NUnit.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="AwesomeAssertions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\tools\K7.Import\K7.Import.csproj" />
    </ItemGroup>

</Project>
