// <auto-generated />
using System;
using K7.Server.Infrastructure.Database.Context.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace K7.Server.Infrastructure.Database.Providers.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323175711_AddUserPinHash")]
    partial class AddUserPinHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeviceUser", b =>
                {
                    b.Property<Guid>("DevicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("DevicesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("DeviceUser");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.BackgroundTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BackgroundTasks");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClientType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceUniqueId")
                        .HasColumnType("text");

                    b.Property<double>("DisplayHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("DisplayWidth")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("integer");

                    b.Property<string>("OperatingSystemVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.ExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonRoleId");

                    b.ToTable("ExternalIds");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.HlsSegment", b =>
                {
                    b.Property<Guid>("FileMetadataId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IndexedFileId")
                        .HasColumnType("uuid");

                    b.Property<long>("StartTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("FileMetadataId", "Number");

                    b.HasIndex("IndexedFileId", "Number");

                    b.ToTable("HlsSegments");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.IndexedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Hash")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSplitPart")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentDirectory")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MediaId");

                    b.ToTable("IndexedFiles");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("RootPathAccessible")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.AudioAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcoustId")
                        .HasColumnType("text");

                    b.Property<double?>("AcoustIdScore")
                        .HasColumnType("double precision");

                    b.Property<int>("AnalysisVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Bpm")
                        .HasColumnType("double precision");

                    b.Property<int?>("ChromaprintDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ChromaprintFingerprint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double?>("Danceability")
                        .HasColumnType("double precision");

                    b.Property<double?>("Energy")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double?>("LoudnessLufs")
                        .HasColumnType("double precision");

                    b.Property<double?>("LoudnessRange")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MusicTrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("MusicalKey")
                        .HasColumnType("text");

                    b.Property<double?>("Valence")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<string>("WaveformPeaks")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MusicTrackId")
                        .IsUnique();

                    b.ToTable("AudioAnalysis");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.BaseMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Medias");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.MetadataPicture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DominantColor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalRemoteUri")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VideoFileMetadataId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("PersonRoleId")
                        .IsUnique();

                    b.HasIndex("PlaylistId")
                        .IsUnique();

                    b.HasIndex("VideoFileMetadataId")
                        .IsUnique();

                    b.ToTable("MetadataPictures");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.MetadataPictureVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MetadataPictureId")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetadataPictureId", "Size")
                        .IsUnique();

                    b.ToTable("MetadataPictureVariants");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("IndexedFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IndexedFileId")
                        .IsUnique();

                    b.ToTable("FileMetadatas");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.BaseFileTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FileTracks");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Deathday")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonRoles");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");

                    b.HasDiscriminator().HasValue("Playlist");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("PlaylistId", "Order");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Ratings.BaseRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("MaximumValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<double>("MinimumValue")
                        .HasColumnType("double precision");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Ratings");

                    b.HasDiscriminator<int>("Source");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Settings.ServerSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Settings.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.StreamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IndexedFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PlaybackSettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IndexedFileId");

                    b.HasIndex("UserId");

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.MediaPlaybackSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "CompletedAt");

                    b.HasIndex("UserId", "MediaId", "CompletedAt");

                    b.ToTable("MediaPlaybackSessions");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PinHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.UserCapabilityOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capability")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCapabilityOverrides");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.UserLibraryExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLibraryExclusions");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.UserMediaState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastInteractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("LastPlaybackPosition")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<double>("ProgressPercentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMediaStates");
                });

            modelBuilder.Entity("K7.Server.Infrastructure.Database.Context.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.Movie", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Medias.BaseMedia");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.MusicAlbum", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Medias.BaseMedia");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.ToTable("Medias", t =>
                        {
                            t.Property("Overview")
                                .HasColumnName("MusicAlbum_Overview");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.MusicTrack", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Medias.BaseMedia");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Lyrics")
                        .HasColumnType("text");

                    b.Property<string>("LyricsLrc")
                        .HasColumnType("text");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasIndex("AlbumId");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.Serie", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Medias.BaseMedia");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.SerieEpisode", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Medias.BaseMedia");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SerieId");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.SerieSeason", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Medias.BaseMedia");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid");

                    b.HasIndex("SerieId");

                    b.ToTable("Medias", t =>
                        {
                            t.Property("SerieId")
                                .HasColumnName("SerieSeason_SerieId");
                        });

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.AudioFileMetadata", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.VideoFileMetadata", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<long>("VideoBitrate")
                        .HasColumnType("bigint");

                    b.Property<int>("VideoResolution")
                        .HasColumnType("integer");

                    b.ToTable("FileMetadatas", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("VideoFileMetadata_Duration");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.AudioFileTrack", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.Files.Tracks.BaseFileTrack");

                    b.Property<Guid?>("AudioFileMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelLayout")
                        .HasColumnType("text");

                    b.Property<int>("Channels")
                        .HasColumnType("integer");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .HasColumnType("text");

                    b.Property<int?>("SampleRateHz")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VideoFileMetadataId")
                        .HasColumnType("uuid");

                    b.HasIndex("AudioFileMetadataId")
                        .IsUnique();

                    b.HasIndex("VideoFileMetadataId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.SubtitleFileTrack", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.Files.Tracks.BaseFileTrack");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsForced")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTextBased")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("VideoFileMetadataId")
                        .HasColumnType("uuid");

                    b.HasIndex("VideoFileMetadataId");

                    b.ToTable("FileTracks", t =>
                        {
                            t.Property("Codec")
                                .HasColumnName("SubtitleFileTrack_Codec");

                            t.Property("Language")
                                .HasColumnName("SubtitleFileTrack_Language");

                            t.Property("Name")
                                .HasColumnName("SubtitleFileTrack_Name");

                            t.Property("VideoFileMetadataId")
                                .HasColumnName("SubtitleFileTrack_VideoFileMetadataId");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.VideoFileTrack", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.Files.Tracks.BaseFileTrack");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("integer");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PixelFormat")
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VideoFileMetadataId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasIndex("VideoFileMetadataId");

                    b.ToTable("FileTracks", t =>
                        {
                            t.Property("Codec")
                                .HasColumnName("VideoFileTrack_Codec");

                            t.Property("Profile")
                                .HasColumnName("VideoFileTrack_Profile");

                            t.Property("VideoFileMetadataId")
                                .HasColumnName("VideoFileTrack_VideoFileMetadataId");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.Actor", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.CrewMember", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.MusicArtist", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.VoiceActor", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PersonRoles", t =>
                        {
                            t.Property("CharacterName")
                                .HasColumnName("VoiceActor_CharacterName");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.SmartPlaylist", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Playlists.Playlist");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Limit")
                        .HasColumnType("integer");

                    b.Property<int>("MatchCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaType")
                        .HasColumnType("integer");

                    b.Property<int>("OrderBy")
                        .HasColumnType("integer");

                    b.Property<bool>("OrderDescending")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("SmartPlaylist");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Ratings.MetadataProviderRating", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Ratings.BaseRating");

                    b.Property<int>("MetadataProvider")
                        .HasColumnType("integer");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Ratings.UserRating", b =>
                {
                    b.HasBaseType("K7.Server.Domain.Entities.Ratings.BaseRating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DeviceUser", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Devices.Device", b =>
                {
                    b.OwnsOne("K7.Server.Domain.Entities.Devices.DevicePlaybackCapabilities", "PlaybackCapabilities", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<string[]>("SupportedMediaFormatIds")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("SupportedSubtitlesCodecs")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<bool>("SupportsHDR")
                                .HasColumnType("boolean");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("K7.Server.Domain.Entities.Devices.NativeDeviceDetails", "NativeDeviceDetails", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("RawDeviceType")
                                .HasColumnType("text");

                            b1.Property<string>("RawIdiom")
                                .HasColumnType("text");

                            b1.Property<string>("RawManufacturer")
                                .HasColumnType("text");

                            b1.Property<string>("RawModel")
                                .HasColumnType("text");

                            b1.Property<string>("RawName")
                                .HasColumnType("text");

                            b1.Property<string>("RawPlatform")
                                .HasColumnType("text");

                            b1.Property<string>("RawVersion")
                                .HasColumnType("text");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("K7.Server.Domain.Entities.Devices.WebDeviceDetails", "WebDeviceDetails", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Browser")
                                .HasColumnType("integer");

                            b1.Property<string>("RawBrowserName")
                                .HasColumnType("text");

                            b1.Property<string>("RawBrowserVersion")
                                .HasColumnType("text");

                            b1.Property<string>("RawEngineName")
                                .HasColumnType("text");

                            b1.Property<string>("RawEngineVersion")
                                .HasColumnType("text");

                            b1.Property<string>("RawOperatingSystemName")
                                .HasColumnType("text");

                            b1.Property<string>("RawOperatingSystemVersion")
                                .HasColumnType("text");

                            b1.Property<string>("RawOperatingSystemVersionName")
                                .HasColumnType("text");

                            b1.Property<string>("RawPlatformType")
                                .HasColumnType("text");

                            b1.Property<string>("RawUserAgent")
                                .HasColumnType("text");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("NativeDeviceDetails");

                    b.Navigation("PlaybackCapabilities")
                        .IsRequired();

                    b.Navigation("WebDeviceDetails");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.ExternalId", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("ExternalIds")
                        .HasForeignKey("MediaId");

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Person", "Person")
                        .WithMany("ExternalIds")
                        .HasForeignKey("PersonId");

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole", "PersonRole")
                        .WithMany("ExternalIds")
                        .HasForeignKey("PersonRoleId");

                    b.Navigation("Media");

                    b.Navigation("Person");

                    b.Navigation("PersonRole");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.HlsSegment", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata", null)
                        .WithMany("HlsSegments")
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.IndexedFile", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Library", null)
                        .WithMany("IndexedFiles")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("IndexedFiles")
                        .HasForeignKey("MediaId");

                    b.OwnsOne("K7.Server.Domain.ValueObjects.MediaIdentification", "Identification", b1 =>
                        {
                            b1.Property<Guid>("IndexedFileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AlbumName")
                                .HasColumnType("text");

                            b1.Property<string>("ArtistName")
                                .HasColumnType("text");

                            b1.Property<DateOnly?>("ReleaseYear")
                                .HasColumnType("date");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("TrackNumber")
                                .HasColumnType("integer");

                            b1.HasKey("IndexedFileId");

                            b1.ToTable("IndexedFiles");

                            b1.WithOwner()
                                .HasForeignKey("IndexedFileId");
                        });

                    b.Navigation("Identification");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.AudioAnalysis", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.MusicTrack", "MusicTrack")
                        .WithOne("AudioAnalysis")
                        .HasForeignKey("K7.Server.Domain.Entities.Medias.AudioAnalysis", "MusicTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicTrack");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.MetadataPicture", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("Pictures")
                        .HasForeignKey("MediaId");

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Person", "Person")
                        .WithOne("PortraitPicture")
                        .HasForeignKey("K7.Server.Domain.Entities.MetadataPicture", "PersonId");

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole", "PersonRole")
                        .WithOne("PortraitPicture")
                        .HasForeignKey("K7.Server.Domain.Entities.MetadataPicture", "PersonRoleId");

                    b.HasOne("K7.Server.Domain.Entities.Playlists.Playlist", "Playlist")
                        .WithOne("CoverPicture")
                        .HasForeignKey("K7.Server.Domain.Entities.MetadataPicture", "PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Files.VideoFileMetadata", "VideoFileMetadata")
                        .WithOne("Thumbnails")
                        .HasForeignKey("K7.Server.Domain.Entities.MetadataPicture", "VideoFileMetadataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Media");

                    b.Navigation("Person");

                    b.Navigation("PersonRole");

                    b.Navigation("Playlist");

                    b.Navigation("VideoFileMetadata");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.MetadataPictureVariant", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.MetadataPicture", "MetadataPicture")
                        .WithMany("Variants")
                        .HasForeignKey("MetadataPictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataPicture");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.IndexedFile", "IndexedFile")
                        .WithOne("FileMetadata")
                        .HasForeignKey("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata", "IndexedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexedFile");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("PersonRoles")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Person", "Person")
                        .WithMany("Roles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.Playlist", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.PlaylistItem", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Playlists.Playlist", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Ratings.BaseRating", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.StreamSession", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.IndexedFile", "IndexedFile")
                        .WithMany()
                        .HasForeignKey("IndexedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("IndexedFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.MediaPlaybackSession", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.UserCapabilityOverride", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Users.User", null)
                        .WithMany("CapabilityOverrides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.UserLibraryExclusion", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Users.User", null)
                        .WithMany("LibraryExclusions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.UserMediaState", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.BaseMedia", "Media")
                        .WithMany("UserMediaStates")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("K7.Server.Infrastructure.Database.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("K7.Server.Infrastructure.Database.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Infrastructure.Database.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("K7.Server.Infrastructure.Database.Context.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.MusicTrack", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.MusicAlbum", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.SerieEpisode", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.SerieSeason", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K7.Server.Domain.Entities.Medias.Serie", "Serie")
                        .WithMany("Episodes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.SerieSeason", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Medias.Serie", "Serie")
                        .WithMany("Seasons")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.AudioFileTrack", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Files.AudioFileMetadata", null)
                        .WithOne("AudioTrack")
                        .HasForeignKey("K7.Server.Domain.Entities.Metadatas.Files.Tracks.AudioFileTrack", "AudioFileMetadataId");

                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Files.VideoFileMetadata", null)
                        .WithMany("AudioTracks")
                        .HasForeignKey("VideoFileMetadataId");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.SubtitleFileTrack", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Files.VideoFileMetadata", null)
                        .WithMany("SubtitleTracks")
                        .HasForeignKey("VideoFileMetadataId");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.Tracks.VideoFileTrack", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Metadatas.Files.VideoFileMetadata", null)
                        .WithMany("VideoTracks")
                        .HasForeignKey("VideoFileMetadataId");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.SmartPlaylist", b =>
                {
                    b.OwnsMany("K7.Server.Domain.Entities.Playlists.SmartPlaylistRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("SmartPlaylistId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Field");

                            b1.Property<int>("Operator");

                            b1.Property<string>("Value");

                            b1.HasKey("SmartPlaylistId", "__synthesizedOrdinal");

                            b1.ToTable("Playlists");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("SmartPlaylistId");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Ratings.UserRating", b =>
                {
                    b.HasOne("K7.Server.Domain.Entities.Users.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.IndexedFile", b =>
                {
                    b.Navigation("FileMetadata");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Library", b =>
                {
                    b.Navigation("IndexedFiles");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.BaseMedia", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("IndexedFiles");

                    b.Navigation("PersonRoles");

                    b.Navigation("Pictures");

                    b.Navigation("Ratings");

                    b.Navigation("UserMediaStates");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.MetadataPicture", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.BaseFileMetadata", b =>
                {
                    b.Navigation("HlsSegments");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Person", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("PortraitPicture");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.PersonRoles.BasePersonRole", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("PortraitPicture");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Playlists.Playlist", b =>
                {
                    b.Navigation("CoverPicture");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("CapabilityOverrides");

                    b.Navigation("LibraryExclusions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.MusicAlbum", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.MusicTrack", b =>
                {
                    b.Navigation("AudioAnalysis");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.Serie", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Medias.SerieSeason", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.AudioFileMetadata", b =>
                {
                    b.Navigation("AudioTrack");
                });

            modelBuilder.Entity("K7.Server.Domain.Entities.Metadatas.Files.VideoFileMetadata", b =>
                {
                    b.Navigation("AudioTracks");

                    b.Navigation("SubtitleTracks");

                    b.Navigation("Thumbnails");

                    b.Navigation("VideoTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
