name: Release drafter

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - branding/**
      - screenshots/**
      - LICENSE
      - .github/FUNDING.yml

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release
        uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
