name: Release drafter

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - branding/**
      - screenshots/**
      - LICENSE
      - .github/FUNDING.yml

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
